### ISSUE TITLE
Cant start addon

### ISSUE THREAD

**Issue by justintv90** [tsudoko/anki-mpv#1]
I did install this addon ( put the .py file into anki addons folder). When i restarted anki, it showing

```
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 41, in loadAddons
    __import__(file.replace(".py", ""))
  File "/home/justin/Documents/Anki/addons/anki-mpv.py", line 7, in <module>
    import mpv
ImportError: No module named mpv
```

I installed pympv from : https://aur.archlinux.org/packages/python-pympv-git/ but it still dont work, please help

**Comment by tsdko** [comment]
Arch's default Python version is 3, right? It's possible the AUR package is py3-only. Try installing pympv manually, remember to use `python2` when installing.

**Comment by justintv90** [comment]
Yeah, i noticed that anki was running on python2 wrapper. I will try to install pympv manually

**Comment by jpf91** [comment]
@justintv90 Here's a modified PKGBUILD:

``` sh
# Maintainer: Ian D, Scott <ian@perebruin.com>
pkgname=python2-pympv-git
pkgver=r97.47b9a7b
pkgrel=1
pkgdesc="A python wrapper for libmpv."
arch=('i686' 'x86_64')
url="https://github.com/andre-d/pympv"
license=('gpl')
depends=('python2')
makedepends=('cython2')
source=('git://github.com/andre-d/pympv.git')
md5sums=('SKIP')
_gitname="pympv"

pkgver () {
  cd $srcdir/$_gitname
  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

package() {
  cd "$srcdir/$_gitname"
  python2 setup.py install --root="$pkgdir"
  install -Dm644 "README.md" "$pkgdir/usr/share/doc/$pkgname/README.md"
}
```

The addon works fine on archlinux with that PKGBUILD installed.

**Comment by tsdko** [comment]
@justintv90 Does it work fine for you now?

**Comment by maxigaz** [comment]
I get the same error as @justintv90, even with the modified PKGBUILD @jpf91 suggested. I'm using Manjaro Linux.

Edit: I also checked out the addon [customPlayer](https://github.com/dae/ankiplugins/blob/master/customPlayer.py), as mentioned in a post on [Reddit](https://www.reddit.com/r/Anki/comments/4c1ihg/does_anyone_use_vlc_with_anki/). It works fine so far.

**Comment by tsdko** [comment]
Anki version? If you use 2.1+, you need to compile pympv for Python 3.
Try copying `mpv.so`/`mpv.cpython-*.so` directly to `Anki/addons`. If it works after copying, it's an issue with the module path.

**Comment by maxigaz** [comment]
Sorry for the late reply! I had the problems I described with Anki 2.0.45 under Manjaro Linux. But as I had various issues with that version of Anki itself, I've installed Anki 2.1.x with pympv for Python 3 (namely the AUR packages `anki` and `python-pympv`). Now your add-on works nicely, without the need to copy any .so files. Thank you!
